name: Update Tokens from Issues

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract issue data
        run: |
          echo "${{ github.event.issue.body }}" > issue.json
          echo "${{ github.event.issue.title }}" > title.txt

      - name: Conditional Step - Title Contains 'Foundations'
        if: contains(github.event.issue.title, 'Foundations')
        run: echo "This is a Foundations request."

      - name: Conditional Step - Title Contains 'Bug'
        if: contains(github.event.issue.title, 'Bug')
        run: echo "This is a bug report."

      - name: Update primitives.json
        run: python update_tokens.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add primitives.json
          git commit -m "Update tokens from issue #${{ github.event.issue.number }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
