name: Update Tokens from Issues

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  
jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract issue data
        run: |
          echo "${{ github.event.issue.body }}" > issue.json

      - name: Update tokens.json
        run: |
          python update_tokens.py

      - name: Commit and push changes
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    git config --global user.name "github-actions"
    git config --global user.email "actions@github.com"
    git add tokens.json
    git commit -m "Update tokens from issue #${{ github.event.issue.number }}" || echo "No changes to commit"
    git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
